name: Build Wheels

on: workflow_dispatch

jobs: 
  build:
    name: Build wheels on Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    # Add ssh-key to clone repository cadical
    - uses: webfactory/ssh-agent@v0.9.0
      with: 
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    # needed for cross-compilation on linux
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19
      with:        
        output-dir: wheelhouse

    - name: Validate wheels
      shell: bash
      run: |
        python -m pip install --upgrade pip twine
        twine check wheelhouse/*.whl
        for w in wheelhouse/*.whl; do zip -T "$w" >/dev/null; done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux
        path: ./wheelhouse/*.whl

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        # unpacks all CIBW artifacts into wheelhouse/
        pattern: wheels-linux
        path: wheelhouse

    - name: Publish package to PyPI
      shell: bash
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install -q --upgrade twine
        twine upload --skip-existing wheelhouse/*.whl --verbose
