name: Build Wheels
on: workflow_dispatch

jobs:
# LINUX
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with: 
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with: { platforms: all }

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      with: { output-dir: wheelhouse }

    - name: Validate wheels
      shell: bash
      run: |
        python -m pip install --upgrade -q pip twine
        twine check wheelhouse/*.whl
        for w in wheelhouse/*.whl; do zip -T "$w" >/dev/null; done

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-linux
        path: wheelhouse/*.whl

# macOS
  build-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with: 
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_BEFORE_ALL_MACOS: |
          brew install libarchive pybind11 make python
          ln -sf "$(brew --prefix make)/libexec/gnubin/make" /usr/local/bin/make
      with: { output-dir: wheelhouse }

    - name: Validate wheels
      shell: bash
      run: |
        python -m pip install --upgrade -q twine
        twine check wheelhouse/*.whl
        for w in wheelhouse/*.whl; do zip -T "$w" >/dev/null; done

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macos
        path: wheelhouse/*.whl

# PUBLISH to PYPI
  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: wheelhouse
        merge-multiple: true

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade -q twine
        twine upload --skip-existing wheelhouse/*.whl --verbose
